server:
  port: 8888
resilience4j.ratelimiter:
  instances:
    transactionService:
      limitForPeriod: 10000  # 每秒允许的最大请求数
      limitRefreshPeriod: 1s  # 限流窗口时间
      timeoutDuration: 100ms  # 请求等待时间
resilience4j.circuitbreaker:
  instances:
    transactionService:
      failureRateThreshold: 50  # 失败率阈值（百分比）
      minimumNumberOfCalls: 10  # 最小调用次数
      slidingWindowSize: 10  # 滑动窗口大小
      waitDurationInOpenState: 10s  # 熔断后等待时间
      permittedNumberOfCallsInHalfOpenState: 5  # 半开状态允许的调用次数